import {
  FaWifi,
  FaParking,
  FaSnowflake,
  FaSortAmountUpAlt,
  FaBed,
  FaBriefcase,
  FaBolt,
  FaCoffee,
  FaDumbbell,
  FaSpa,
  FaSwimmingPool,
  FaUmbrellaBeach,
  FaShuttleVan,
  FaSoap,
  FaWheelchair,
} from "react-icons/fa";
import {
  MdRoomService,
  MdAccessTime,
  MdTv,
  MdRestaurant,
  MdFreeBreakfast,
  MdPets,
  MdAccessible,
  MdFamilyRestroom,
} from "react-icons/md";
import { RiSafe2Line } from "react-icons/ri";
import { GiHotSurface, GiSuitcase, GiKidSlide } from "react-icons/gi";

import { IconType } from "react-icons";
import { IconKey, Tag } from "../_types/types";

export const availableTags: Tag[] = [
  { icon: "FaWifi", label: "Free Wi-Fi" },
  { icon: "FaParking", label: "Parking" },
  { icon: "FaSnowflake", label: "Air Conditioning" },
  { icon: "FaSortAmountUpAlt", label: "Elevator" },
  { icon: "MdRoomService", label: "Room Service" },
  { icon: "MdAccessTime", label: "24/7 Reception" },
  { icon: "FaBed", label: "Bed" },
  { icon: "MdTv", label: "TV" },
  { icon: "RiSafe2Line", label: "Safe Box" },
  { icon: "FaBriefcase", label: "Business Center" },
  { icon: "FaBolt", label: "Fast Internet" },
  { icon: "MdRestaurant", label: "Restaurant" },
  { icon: "MdFreeBreakfast", label: "Free Breakfast" },
  { icon: "FaCoffee", label: "Coffee/Tea" },
  { icon: "FaDumbbell", label: "Gym" },
  { icon: "FaSpa", label: "Spa" },
  { icon: "FaSwimmingPool", label: "Swimming Pool" },
  { icon: "GiHotSurface", label: "Sauna" },
  { icon: "FaUmbrellaBeach", label: "Beach Access" },
  { icon: "GiSuitcase", label: "Luggage Storage" },
  { icon: "FaShuttleVan", label: "Airport Shuttle" },
  { icon: "FaSoap", label: "Laundry Service" },
  { icon: "MdPets", label: "Pet Friendly" },
  { icon: "FaWheelchair", label: "Wheelchair Accessible" },
  { icon: "MdAccessible", label: "Accessible Bathroom" },
  { icon: "MdFamilyRestroom", label: "Family Rooms" },
  { icon: "GiKidSlide", label: "Kids Playground" },
];

export const iconMap: Record<IconKey, IconType> = {
  FaWifi,
  FaParking,
  FaSnowflake,
  FaSortAmountUpAlt,
  FaBed,
  FaBriefcase,
  FaBolt,
  FaCoffee,
  FaDumbbell,
  FaSpa,
  FaSwimmingPool,
  FaUmbrellaBeach,
  FaShuttleVan,
  FaSoap,
  FaWheelchair,
  MdRoomService,
  MdAccessTime,
  MdTv,
  MdRestaurant,
  MdFreeBreakfast,
  MdPets,
  MdAccessible,
  MdFamilyRestroom,
  RiSafe2Line,
  GiHotSurface,
  GiSuitcase,
  GiKidSlide,
};
