import {
  FaWifi,
  FaParking,
  FaSnowflake,
  FaBed,
  FaBolt,
  FaCoffee,
  FaDumbbell,
  FaSpa,
  FaSwimmingPool,
  FaUmbrellaBeach,
  FaShuttleVan,
  FaSoap,
  FaWheelchair,
} from "react-icons/fa";
import {
  MdRoomService,
  MdAccessTime,
  MdTv,
  MdRestaurant,
  MdFoodBank,
  MdPets,
  MdAccessible,
  MdFamilyRestroom,
} from "react-icons/md";
import { RiSafe2Line } from "react-icons/ri";
import { GiHotSurface, GiSuitcase, GiKidSlide } from "react-icons/gi";

import { IconType } from "react-icons";
import { IconKey, Tag } from "../_types/types";

export const availableTags: Tag[] = [
  {
    icon: "FaWifi",
    labels: [
      "Free Wi-Fi",
      "واي فاي مجاني",
      "Wi-Fi gratuit",
      "Kostenloses WLAN",
      "Wi-Fi gratis",
      "Wi-Fi gratuito",
    ],
  },
  {
    icon: "FaParking",
    labels: [
      "Parking",
      "موقف سيارات",
      "Parkplatz",
      "Aparcamiento",
      "Parcheggio",
      "Parken",
      "Estacionamiento",
    ],
  },
  {
    icon: "FaSnowflake",
    labels: [
      "Air Conditioning",
      "تكييف هواء",
      "تكييف الهواء",
      "Climatisation",
      "Klimaanlage",
      "Aire acondicionado",
      "Aria condizionata",
    ],
  },
  {
    icon: "MdRoomService",
    labels: [
      "Room Service",
      "خدمة الغرف",
      "Service en chambre",
      "Zimmerservice",
      "Servicio de habitaciones",
      "Servizio in camera",
      "Service d'étage",
    ],
  },
  {
    icon: "MdAccessTime",
    labels: [
      "24/7 Reception",
      "استقبال على مدار الساعة طوال أيام الأسبوع",
      "استقبال على مدار الساعة",
      "Réception 24h/24 et 7j/7",
      "24/7-Rezeption",
      "Recepción 24/7",
      "Reception 24 ore su 24, 7 giorni su 7",
      "Reception 24 ore su 24",
    ],
  },
  {
    icon: "FaBed",
    labels: ["Bed", "السرير", "سرير", "Lit", "Bett", "Cama", "Letto"],
  },
  {
    icon: "MdTv",
    labels: ["TV", "تلفزيون", "Télévision"],
  },
  {
    icon: "RiSafe2Line",
    labels: [
      "Safe Box",
      "خزنة",
      "Coffre-fort",
      "Safe",
      "Caja de seguridad",
      "Cassaforte",
    ],
  },
  // {
  //   icon: "FaBriefcase",
  //   labels: [
  //     "Business Center",
  //     "مركز أعمال",
  //     "Centre d'affaires",
  //     "Businesscenter",
  //     "Centro de negocios",
  //     "Centro business",
  //   ],
  // },
  {
    icon: "FaBolt",
    labels: [
      "Fast Internet",
      "إنترنت سريع",
      "Internet rapide",
      "Schnelles Internet",
      "Internet rápido",
      "Internet veloce",
    ],
  },
  {
    icon: "MdRestaurant",
    labels: ["Restaurant", "مطعم", "المطعم", "Restaurante", "Ristorante"],
  },
  {
    icon: "MdFoodBank",
    labels: [
      "Free Breakfast",
      "إفطار مجاني",
      "Petit-déjeuner gratuit",
      "Kostenloses Frühstück",
      "Desayuno gratuito",
      "Colazione gratuita",
      "Desayuno gratis",
    ],
  },
  {
    icon: "FaCoffee",
    labels: [
      "Coffee/Tea",
      "قهوة/شاي",
      "القهوة/الشاي",
      "Café/Thé",
      "Kaffee/Tee",
      "Café/Té",
      "Café/té",
      "Caffè/Tè",
    ],
  },
  {
    icon: "FaDumbbell",
    labels: [
      "Gym",
      "صالة ألعاب رياضية",
      "صالة الألعاب الرياضية",
      "Salle de sport",
      "Fitnessstudio",
      "Fitnessraum",
      "Gimnasio",
      "Palestra",
    ],
  },
  {
    icon: "FaSpa",
    labels: ["Spa", "منتجع صحي", "سبا"],
  },
  {
    icon: "FaSwimmingPool",
    labels: [
      "Swimming Pool",
      "حمام سباحة",
      "حمام السباحة",
      "Piscine",
      "Schwimmbad",
      "Piscina",
    ],
  },
  {
    icon: "GiHotSurface",
    labels: ["Sauna", "ساونا", "Sauna", "Sauna", "Sauna", "Sauna"],
  },
  {
    icon: "FaUmbrellaBeach",
    labels: [
      "Beach Access",
      "إمكانية الوصول إلى الشاطئ",
      "Accès à la plage",
      "Zugang zum Strand",
      "Acceso a la playa",
      "Accesso alla spiaggia",
    ],
  },
  {
    icon: "GiSuitcase",
    labels: [
      "Luggage Storage",
      "تخزين الأمتعة",
      "Consignation des bagages",
      "Gepäckaufbewahrung",
      "Consigna de equipaje",
      "Deposito bagagli",
    ],
  },
  {
    icon: "FaShuttleVan",
    labels: [
      "Airport Shuttle",
      "خدمة نقل المطار",
      "Navette aéroport",
      "Flughafen-Shuttle",
      "Transporte al aeropuerto",
      "Navetta aeroportuale",
      "Servicio de transporte al aeropuerto",
      "Traslado al aeropuerto",
    ],
  },
  {
    icon: "FaSoap",
    labels: [
      "Laundry Service",
      "خدمة غسيل الملابس",
      "Service de blanchisserie",
      "Wäscheservice",
      "Servicio de lavandería",
      "Servizio lavanderia",
    ],
  },
  {
    icon: "MdPets",
    labels: [
      "Pet Friendly",
      "مسموح بالحيوانات الأليفة",
      "مسموح باصطحاب الحيوانات الأليفة",
      "مناسب للحيوانات الأليفة",
      "Animaux acceptés",
      "Haustiere erlaubt",
      "Se admiten mascotas",
      "Animali ammessi",
    ],
  },
  {
    icon: "FaWheelchair",
    labels: [
      "Wheelchair Accessible",
      "ملائم للكراسي المتحركة",
      "مناسب للكراسي المتحركة",
      "Accessible aux fauteuils roulants",
      "Rollstuhlgerecht",
      "Acceso para sillas de ruedas",
      "Accessibile alle sedie a rotelle",
    ],
  },
  {
    icon: "MdAccessible",
    labels: [
      "Accessible Bathroom",
      "حمام مناسب للكراسي المتحركة",
      "حمام مناسب لذوي الاحتياجات الخاصة",
      "حمام مُيسّر",
      "Salle de bain accessible",
      "Barrierefreies Badezimmer",
      "Baño accesible",
      "Bagno accessibile",
    ],
  },
  {
    icon: "MdFamilyRestroom",
    labels: [
      "Family Rooms",
      "غرف عائلية",
      "Chambres familiales",
      "Familienzimmer",
      "Habitaciones familiares",
      "Camere familiari",
      "Camere per famiglie",
    ],
  },
  {
    icon: "GiKidSlide",
    labels: [
      "Kids Playground",
      "ملعب للأطفال",
      "Aire de jeux pour enfants",
      "Kinderspielplatz",
      "Parque infantil",
      "Area giochi per bambini",
    ],
  },
];

export const iconMap: Record<IconKey, IconType> = {
  FaWifi,
  FaParking,
  FaSnowflake,
  FaBed,
  FaBolt,
  FaCoffee,
  FaDumbbell,
  FaSpa,
  FaSwimmingPool,
  FaUmbrellaBeach,
  FaShuttleVan,
  FaSoap,
  FaWheelchair,
  MdRoomService,
  MdAccessTime,
  MdTv,
  MdRestaurant,
  MdFoodBank,
  MdPets,
  MdAccessible,
  MdFamilyRestroom,
  RiSafe2Line,
  GiHotSurface,
  GiSuitcase,
  GiKidSlide,
};
