import {
  FaWifi,
  FaParking,
  FaSnowflake,
  FaSortAmountUpAlt,
  FaBed,
  FaBriefcase,
  FaBolt,
  FaCoffee,
  FaDumbbell,
  FaSpa,
  FaSwimmingPool,
  FaUmbrellaBeach,
  FaShuttleVan,
  FaSoap,
  FaWheelchair,
} from "react-icons/fa";
import {
  MdRoomService,
  MdAccessTime,
  MdTv,
  MdRestaurant,
  MdFreeBreakfast,
  MdPets,
  MdAccessible,
  MdFamilyRestroom,
} from "react-icons/md";
import { RiSafe2Line } from "react-icons/ri";
import { GiHotSurface, GiSuitcase, GiKidSlide } from "react-icons/gi";

import { IconType } from "react-icons";
import { IconKey, Tag } from "../_types/types";

export const availableTags: Tag[] = [
  { icon: "FaWifi", label: "Free Wi-Fi" },
  { icon: "FaParking", label: "Parking" },
  { icon: "FaSnowflake", label: "Air Conditioning" },
  { icon: "FaSortAmountUpAlt", label: "Elevator" },
  { icon: "MdRoomService", label: "Room Service" },
  { icon: "MdAccessTime", label: "24/7 Reception" },
  { icon: "FaBed", label: "Bed" },
  { icon: "MdTv", label: "TV" },
  { icon: "RiSafe2Line", label: "Safe Box" },
  { icon: "FaBriefcase", label: "Business Center" },
  { icon: "FaBolt", label: "Fast Internet" },
  { icon: "MdRestaurant", label: "Restaurant" },
  { icon: "MdFreeBreakfast", label: "Free Breakfast" },
  { icon: "FaCoffee", label: "Coffee/Tea" },
  { icon: "FaDumbbell", label: "Gym" },
  { icon: "FaSpa", label: "Spa" },
  { icon: "FaSwimmingPool", label: "Swimming Pool" },
  { icon: "GiHotSurface", label: "Sauna" },
  { icon: "FaUmbrellaBeach", label: "Beach Access" },
  { icon: "GiSuitcase", label: "Luggage Storage" },
  { icon: "FaShuttleVan", label: "Airport Shuttle" },
  { icon: "FaSoap", label: "Laundry Service" },
  { icon: "MdPets", label: "Pet Friendly" },
  { icon: "FaWheelchair", label: "Wheelchair Accessible" },
  { icon: "MdAccessible", label: "Accessible Bathroom" },
  { icon: "MdFamilyRestroom", label: "Family Rooms" },
  { icon: "GiKidSlide", label: "Kids Playground" },
];

export const iconMap: Record<IconKey, IconType> = {
  FaWifi,
  FaParking,
  FaSnowflake,
  FaSortAmountUpAlt,
  FaBed,
  FaBriefcase,
  FaBolt,
  FaCoffee,
  FaDumbbell,
  FaSpa,
  FaSwimmingPool,
  FaUmbrellaBeach,
  FaShuttleVan,
  FaSoap,
  FaWheelchair,
  MdRoomService,
  MdAccessTime,
  MdTv,
  MdRestaurant,
  MdFreeBreakfast,
  MdPets,
  MdAccessible,
  MdFamilyRestroom,
  RiSafe2Line,
  GiHotSurface,
  GiSuitcase,
  GiKidSlide,
};

// import {
//   FaWifi,
//   FaParking,
//   FaSnowflake,
//   FaSortAmountUpAlt,
//   FaBed,
//   FaBriefcase,
//   FaBolt,
//   FaCoffee,
//   FaDumbbell,
//   FaSpa,
//   FaSwimmingPool,
//   FaUmbrellaBeach,
//   FaShuttleVan,
//   FaSoap,
//   FaWheelchair,
// } from "react-icons/fa";
// import {
//   MdRoomService,
//   MdAccessTime,
//   MdTv,
//   MdRestaurant,
//   MdFreeBreakfast,
//   MdPets,
//   MdAccessible,
//   MdFamilyRestroom,
// } from "react-icons/md";
// import { RiSafe2Line } from "react-icons/ri";
// import { GiHotSurface, GiSuitcase, GiKidSlide } from "react-icons/gi";

// import { IconType } from "react-icons";
// import { IconKey, Tag } from "../_types/types";

// export const availableTags: Tag[] = [
//   {
//     icon: "FaWifi",
//     labels: [
//       "Free Wi-Fi",
//       "واي فاي مجاني",
//       "Wi-Fi gratuit",
//       "Kostenloses WLAN",
//       "Wi-Fi gratis",
//       "Wi-Fi gratuito",
//     ],
//   },
//   {
//     icon: "FaParking",
//     labels: [
//       "Parking",
//       "موقف سيارات",
//       "Parking",
//       "Parkplatz",
//       "Aparcamiento",
//       "Parcheggio",
//     ],
//   },
//   {
//     icon: "FaSnowflake",
//     labels: [
//       "Air Conditioning",
//       "تكييف هواء",
//       "Climatisation",
//       "Klimaanlage",
//       "Aire acondicionado",
//       "Aria condizionata",
//     ],
//   },
//   {
//     icon: "FaSortAmountUpAlt",
//     labels: [
//       "Elevator",
//       "مصعد",
//       "Ascenseur",
//       "Aufzug",
//       "Ascensor",
//       "Ascensore",
//     ],
//   },
//   {
//     icon: "MdRoomService",
//     labels: [
//       "Room Service",
//       "خدمة الغرف",
//       "Service en chambre",
//       "Zimmerservice",
//       "Servicio de habitaciones",
//       "Servizio in camera",
//     ],
//   },
//   {
//     icon: "MdAccessTime",
//     labels: [
//       "24/7 Reception",
//       "استقبال 24/7",
//       "Réception 24h/24",
//       "Rezeption rund um die Uhr",
//       "Recepción 24 horas",
//       "Reception 24/7",
//     ],
//   },
//   { icon: "FaBed", labels: ["Bed", "سرير", "Lit", "Bett", "Cama", "Letto"] },
//   {
//     icon: "MdTv",
//     labels: [
//       "TV",
//       "تلفزيون",
//       "Télévision",
//       "Fernseher",
//       "Televisión",
//       "Televisore",
//     ],
//   },
//   {
//     icon: "RiSafe2Line",
//     labels: [
//       "Safe Box",
//       "خزنة",
//       "Coffre-fort",
//       "Safe",
//       "Caja fuerte",
//       "Cassaforte",
//     ],
//   },
//   {
//     icon: "FaBriefcase",
//     labels: [
//       "Business Center",
//       "مركز أعمال",
//       "Centre d'affaires",
//       "Businesscenter",
//       "Centro de negocios",
//       "Centro business",
//     ],
//   },
//   {
//     icon: "FaBolt",
//     labels: [
//       "Fast Internet",
//       "انترنت سريع",
//       "Internet rapide",
//       "Schnelles Internet",
//       "Internet rápido",
//       "Internet veloce",
//     ],
//   },
//   {
//     icon: "MdRestaurant",
//     labels: [
//       "Restaurant",
//       "مطعم",
//       "Restaurant",
//       "Restaurant",
//       "Restaurante",
//       "Ristorante",
//     ],
//   },
//   {
//     icon: "MdFreeBreakfast",
//     labels: [
//       "Free Breakfast",
//       "إفطار مجاني",
//       "Petit-déjeuner gratuit",
//       "Kostenloses Frühstück",
//       "Desayuno gratuito",
//       "Colazione gratuita",
//     ],
//   },
//   {
//     icon: "FaCoffee",
//     labels: [
//       "Coffee/Tea",
//       "قهوة/شاي",
//       "Café/Thé",
//       "Kaffee/Tee",
//       "Café/Té",
//       "Caffè/Tè",
//     ],
//   },
//   {
//     icon: "FaDumbbell",
//     labels: [
//       "Gym",
//       "صالة رياضية",
//       "Salle de sport",
//       "Fitnessstudio",
//       "Gimnasio",
//       "Palestra",
//     ],
//   },
//   { icon: "FaSpa", labels: ["Spa", "منتجع صحي", "Spa", "Spa", "Spa", "Spa"] },
//   {
//     icon: "FaSwimmingPool",
//     labels: [
//       "Swimming Pool",
//       "حمام سباحة",
//       "Piscine",
//       "Schwimmbad",
//       "Piscina",
//       "Piscina",
//     ],
//   },
//   {
//     icon: "GiHotSurface",
//     labels: ["Sauna", "ساونا", "Sauna", "Sauna", "Sauna", "Sauna"],
//   },
//   {
//     icon: "FaUmbrellaBeach",
//     labels: [
//       "Beach Access",
//       "دخول الشاطئ",
//       "Accès à la plage",
//       "Strandzugang",
//       "Acceso a la playa",
//       "Accesso alla spiaggia",
//     ],
//   },
//   {
//     icon: "GiSuitcase",
//     labels: [
//       "Luggage Storage",
//       "تخزين الأمتعة",
//       "Consigne à bagages",
//       "Gepäckaufbewahrung",
//       "Consigna de equipaje",
//       "Deposito bagagli",
//     ],
//   },
//   {
//     icon: "FaShuttleVan",
//     labels: [
//       "Airport Shuttle",
//       "خدمة النقل من/إلى المطار",
//       "Navette aéroport",
//       "Flughafenshuttle",
//       "Transporte al aeropuerto",
//       "Navetta aeroportuale",
//     ],
//   },
//   {
//     icon: "FaSoap",
//     labels: [
//       "Laundry Service",
//       "خدمة غسيل الملابس",
//       "Service de blanchisserie",
//       "Wäscheservice",
//       "Servicio de lavandería",
//       "Servizio lavanderia",
//     ],
//   },
//   {
//     icon: "MdPets",
//     labels: [
//       "Pet Friendly",
//       "مسموح بالحيوانات",
//       "Animaux acceptés",
//       "Haustierfreundlich",
//       "Admite mascotas",
//       "Animali ammessi",
//     ],
//   },
//   {
//     icon: "FaWheelchair",
//     labels: [
//       "Wheelchair Accessible",
//       "مناسب للكراسي المتحركة",
//       "Accès fauteuil roulant",
//       "Rollstuhlgerecht",
//       "Accesible para sillas de ruedas",
//       "Accessibile in sedia a rotelle",
//     ],
//   },
//   {
//     icon: "MdAccessible",
//     labels: [
//       "Accessible Bathroom",
//       "حمام مناسب",
//       "Salle de bain accessible",
//       "Barrierefreies Badezimmer",
//       "Baño accesible",
//       "Bagno accessibile",
//     ],
//   },
//   {
//     icon: "MdFamilyRestroom",
//     labels: [
//       "Family Rooms",
//       "غرف عائلية",
//       "Chambres familiales",
//       "Familienzimmer",
//       "Habitaciones familiares",
//       "Camere familiari",
//     ],
//   },
//   {
//     icon: "GiKidSlide",
//     labels: [
//       "Kids Playground",
//       "ملعب أطفال",
//       "Aire de jeux pour enfants",
//       "Kinderspielplatz",
//       "Parque infantil",
//       "Parco giochi per bambini",
//     ],
//   },
// ];

// export const iconMap: Record<IconKey, IconType> = {
//   FaWifi,
//   FaParking,
//   FaSnowflake,
//   FaSortAmountUpAlt,
//   FaBed,
//   FaBriefcase,
//   FaBolt,
//   FaCoffee,
//   FaDumbbell,
//   FaSpa,
//   FaSwimmingPool,
//   FaUmbrellaBeach,
//   FaShuttleVan,
//   FaSoap,
//   FaWheelchair,
//   MdRoomService,
//   MdAccessTime,
//   MdTv,
//   MdRestaurant,
//   MdFreeBreakfast,
//   MdPets,
//   MdAccessible,
//   MdFamilyRestroom,
//   RiSafe2Line,
//   GiHotSurface,
//   GiSuitcase,
//   GiKidSlide,
// };
